package Controlador;
import Conexion.Conexion; import Modelo.*; import java.sql.*; import java.util.*;
public class FichaClinicaDAO {
 public int enfermeraDeUsuario(int usuarioId){String q="SELECT idenfermeras FROM enfermeras WHERE Usuarios_idUsuarios=?";try(Connection c=new Conexion().getConexion();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,usuarioId);try(ResultSet r=p.executeQuery()){return r.next()?r.getInt(1):0;}}catch(SQLException e){return 0;}}
 public boolean puedeVer(int paciente,int enfermera){String q="SELECT 1 FROM atencion WHERE Paciente_idPaciente=? AND enfermeras_idenfermeras=? LIMIT 1";try(Connection c=new Conexion().getConexion();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,paciente);p.setInt(2,enfermera);try(ResultSet r=p.executeQuery()){return r.next();}}catch(SQLException e){return false;}}
 public List<EventoClinico> eventos(int paciente){List<EventoClinico> l=new ArrayList<>();String q="SELECT h.fecha,h.tipo,h.descripcion,CONCAT(u.nombres,' ',u.apellidos) enfermera FROM historial_clinico h JOIN enfermeras e ON e.idenfermeras=h.enfermera_idenfermeras JOIN usuarios u ON u.idUsuarios=e.Usuarios_idUsuarios WHERE h.paciente_idPaciente=? ORDER BY h.fecha DESC";try(Connection c=new Conexion().getConexion();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,paciente);try(ResultSet r=p.executeQuery()){while(r.next()){EventoClinico x=new EventoClinico();x.fecha=r.getTimestamp(1);x.tipo=r.getString(2);x.descripcion=r.getString(3);x.enfermera=r.getString(4);l.add(x);}}}catch(SQLException e){}return l;}
 public List<SignoVital> signos(int paciente){List<SignoVital> l=new ArrayList<>();String q="SELECT fecha_hora,presion_arterial,frecuencia_cardiaca,temperatura,saturacion_oxigeno,glucosa FROM signos_vitales WHERE paciente_idPaciente=? ORDER BY fecha_hora DESC";try(Connection c=new Conexion().getConexion();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,paciente);try(ResultSet r=p.executeQuery()){while(r.next()){SignoVital s=new SignoVital();s.fecha=r.getTimestamp(1);s.presion=r.getString(2);s.frecuencia=(Integer)r.getObject(3);s.temperatura=numero(r.getObject(4));s.saturacion=numero(r.getObject(5));s.glucosa=numero(r.getObject(6));l.add(s);}}}catch(SQLException e){}return l;}
 private Double numero(Object valor){return valor instanceof Number ? ((Number)valor).doubleValue() : null;}
 public List<EventoClinico> notas(int paciente){List<EventoClinico> l=new ArrayList<>();String q="SELECT b.fecha_hora,b.nota,CONCAT(u.nombres,' ',u.apellidos) FROM bitacora_enfermeria b JOIN enfermeras e ON e.idenfermeras=b.enfermera_idenfermeras JOIN usuarios u ON u.idUsuarios=e.Usuarios_idUsuarios WHERE b.paciente_idPaciente=? ORDER BY b.fecha_hora DESC";try(Connection c=new Conexion().getConexion();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,paciente);try(ResultSet r=p.executeQuery()){while(r.next()){EventoClinico x=new EventoClinico();x.fecha=r.getTimestamp(1);x.descripcion=r.getString(2);x.enfermera=r.getString(3);l.add(x);}}}catch(SQLException e){}return l;}
 public ContactoEmergencia contacto(int paciente){String q="SELECT nombre,parentesco,telefono,direccion FROM contacto_emergencia WHERE paciente_idPaciente=?";try(Connection c=new Conexion().getConexion();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,paciente);try(ResultSet r=p.executeQuery()){if(r.next()){ContactoEmergencia x=new ContactoEmergencia();x.nombre=r.getString(1);x.parentesco=r.getString(2);x.telefono=r.getString(3);x.direccion=r.getString(4);return x;}}}catch(SQLException e){}return null;}
 public boolean insertar(String q,Object...v){try(Connection c=new Conexion().getConexion();PreparedStatement p=c.prepareStatement(q)){for(int i=0;i<v.length;i++)p.setObject(i+1,v[i]);return p.executeUpdate()>0;}catch(SQLException e){System.out.println(e.getMessage());return false;}}
}
