package Servlet;
import Controlador.*; import Modelo.*; import jakarta.servlet.annotation.WebServlet; import jakarta.servlet.http.*; import jakarta.servlet.*; import java.io.*; import java.sql.Timestamp;
@WebServlet("/FichaPaciente") public class FichaPacienteServlet extends HttpServlet {
 private boolean acceso(HttpServletRequest r,HttpServletResponse s,int paciente)throws IOException{Object o=r.getSession(false)==null?null:r.getSession(false).getAttribute("usuario");if(!(o instanceof Usuarios)){s.sendRedirect(r.getContextPath()+"/Index.jsp");return false;}Usuarios u=(Usuarios)o;if(u.getRolDescripcion()==null||!u.getRolDescripcion().toLowerCase().contains("enfermer")){s.sendRedirect(r.getContextPath()+"/Index.jsp");return false;}FichaClinicaDAO d=new FichaClinicaDAO();if(!d.puedeVer(paciente,d.enfermeraDeUsuario(u.getid_Usuarios()))){s.sendRedirect(r.getContextPath()+"/GestionPacientes");return false;}return true;}
 protected void doGet(HttpServletRequest r,HttpServletResponse s)throws ServletException,IOException{int id=num(r,"id");if(id<=0||!acceso(r,s,id))return;FichaClinicaDAO d=new FichaClinicaDAO();Paciente p=new PacienteDAO().consultarPaciente(id);if(p==null){s.sendRedirect(r.getContextPath()+"/GestionPacientes");return;}r.setAttribute("paciente",p);r.setAttribute("eventos",d.eventos(id));r.setAttribute("signos",d.signos(id));r.setAttribute("notas",d.notas(id));r.setAttribute("contacto",d.contacto(id));r.getRequestDispatcher("/Vista/FichaPacienteVista.jsp").forward(r,s);}
 protected void doPost(HttpServletRequest r,HttpServletResponse s)throws IOException{r.setCharacterEncoding("UTF-8");int id=num(r,"paciente_id");if(id<=0||!acceso(r,s,id))return;Usuarios u=(Usuarios)r.getSession().getAttribute("usuario");int e=new FichaClinicaDAO().enfermeraDeUsuario(u.getid_Usuarios());FichaClinicaDAO d=new FichaClinicaDAO();String a=limpiar(r,"accion");if("historial".equals(a)||"nota".equals(a)||"signos".equals(a)){String fecha=limpiar(r,"fecha_hora");if(fecha.isEmpty()){s.sendRedirect(r.getContextPath()+"/FichaPaciente?id="+id);return;}Timestamp ahora=Timestamp.valueOf(fecha.replace('T',' ')+":00");if("historial".equals(a))d.insertar("INSERT INTO historial_clinico(paciente_idPaciente,enfermera_idenfermeras,fecha,tipo,descripcion)VALUES(?,?,?,?,?)",id,e,ahora,limpiar(r,"tipo"),limpiar(r,"descripcion"));else if("nota".equals(a))d.insertar("INSERT INTO bitacora_enfermeria(paciente_idPaciente,enfermera_idenfermeras,fecha_hora,nota)VALUES(?,?,?,?)",id,e,ahora,limpiar(r,"nota"));else d.insertar("INSERT INTO signos_vitales(paciente_idPaciente,enfermera_idenfermeras,fecha_hora,presion_arterial,frecuencia_cardiaca,temperatura,saturacion_oxigeno,glucosa)VALUES(?,?,?,?,?,?,?,?)",id,e,ahora,limpiar(r,"presion"),num(r,"frecuencia"),limpiar(r,"temperatura"),limpiar(r,"saturacion"),limpiar(r,"glucosa"));}else if("contacto".equals(a))d.insertar("INSERT INTO contacto_emergencia(paciente_idPaciente,nombre,parentesco,telefono,direccion)VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE nombre=VALUES(nombre),parentesco=VALUES(parentesco),telefono=VALUES(telefono),direccion=VALUES(direccion)",id,limpiar(r,"nombre"),limpiar(r,"parentesco"),limpiar(r,"telefono"),limpiar(r,"direccion"));s.sendRedirect(r.getContextPath()+"/FichaPaciente?id="+id);}
 private String limpiar(HttpServletRequest r,String n){String v=r.getParameter(n);return v==null?"":v.trim();}
 private int num(HttpServletRequest r,String n){try{return Integer.parseInt(r.getParameter(n));}catch(Exception e){return 0;}}
}
